language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: jruby-19mode
      env: XML=nokogiri
notifications:
  email:
    recipients:
      - dev@recurly.com
branches:
  only:
    - master
